LOCAL_PATH := $(call my-dir)

BASE_GFX_DIR := ufo_byt
TARGET_OUT_ORIG := $(TARGET_OUT)
TARGET_OUT := $(TARGET_OUT_ORIG)/vendor/gfx/$(BASE_GFX_DIR)
#TARGET_OUT_ETC:= $(TARGET_OUT)/etc
TARGET_OUT_EXECUTABLES:= $(TARGET_OUT)/bin
TARGET_OUT_SHARED_LIBRARIES:= $(TARGET_OUT)/lib

include $(LOCAL_PATH)/$(TARGET_ARCH)/baytrail.mk

TARGET_OUT := $(TARGET_OUT_ORIG)
#TARGET_OUT_ETC:= $(TARGET_OUT)/etc
TARGET_OUT_EXECUTABLES:= $(TARGET_OUT)/bin
TARGET_OUT_SHARED_LIBRARIES:= $(TARGET_OUT)/lib

include $(LOCAL_PATH)/ufo_autodetect_links.mk
