ifneq ($(BOARD_HAVE_GEN_GFX_SRC),true)

include $(CLEAR_VARS)
LOCAL_MODULE := ufo_prebuilts
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := intel
LOCAL_REQUIRED_MODULES :=
LOCAL_REQUIRED_MODULES += coreu
LOCAL_REQUIRED_MODULES += mediainfo
LOCAL_REQUIRED_MODULES += hwc.ufo
LOCAL_REQUIRED_MODULES += libhwcservice_vpg
LOCAL_REQUIRED_MODULES += libs3cjpeg_vpg
LOCAL_REQUIRED_MODULES += gralloc.ufo
LOCAL_REQUIRED_MODULES += libgrallocclient
LOCAL_REQUIRED_MODULES += libgrallocgmm
LOCAL_REQUIRED_MODULES += libGLES_ufo_intel7
LOCAL_REQUIRED_MODULES += i965_drv_video
LOCAL_REQUIRED_MODULES += libpcp
LOCAL_REQUIRED_MODULES += libpavpdll
LOCAL_REQUIRED_MODULES += libivp
LOCAL_REQUIRED_MODULES += lib2d
LOCAL_REQUIRED_MODULES += libcoreuclient
LOCAL_REQUIRED_MODULES += libcoreuinterface
LOCAL_REQUIRED_MODULES += libcoreuservice
LOCAL_REQUIRED_MODULES += libgsmgr
LOCAL_REQUIRED_MODULES += libskuwa
LOCAL_REQUIRED_MODULES += libmd
LOCAL_REQUIRED_MODULES += libuevent

#add from 32
LOCAL_REQUIRED_MODULES += igfxcmjit32
LOCAL_REQUIRED_MODULES += igfxcmrt32
# Non-VPG deps
LOCAL_REQUIRED_MODULES += libdrm
LOCAL_REQUIRED_MODULES += libdrm_intel
LOCAL_REQUIRED_MODULES += libpciaccess
LOCAL_REQUIRED_MODULES += libva
LOCAL_REQUIRED_MODULES += libva-android
include $(BUILD_PHONY_PACKAGE)

include $(CLEAR_VARS)
LOCAL_MODULE := coreu
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := intel
LOCAL_SRC_FILES := x86_64/coreu
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mediainfo
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := intel
LOCAL_SRC_FILES := x86_64/mediainfo
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS_TO := ufo
LOCAL_COPY_HEADERS := x86/graphics.h
LOCAL_COPY_HEADERS += x86/gralloc.h
LOCAL_COPY_HEADERS += x86/iVP.h
include $(BUILD_COPY_HEADERS)

# The intersection of the library sets are placed at this level, the rest of
# the libraries are handled in the board platform make files which should be
# conditionally included from this file if present.

# Hardware Composer
include $(CLEAR_VARS)
LOCAL_MODULE := hwc.ufo
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_MODULE_STEM_32 := hwcomposer.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_STEM_64 := hwcomposer.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/hwcomposer$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/hwcomposer$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

# Hardware Composer Service
include $(CLEAR_VARS)
LOCAL_MODULE := libhwcservice_vpg
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM_32 := libhwcservice
LOCAL_MODULE_STEM_64 := libhwcservice
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/libhwcservice$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/libhwcservice$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

# gralloc
include $(CLEAR_VARS)
LOCAL_MODULE := gralloc.ufo
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_MODULE_STEM_32 := gralloc.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_STEM_64 := gralloc.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/gralloc$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/gralloc$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

# grallocclient
include $(CLEAR_VARS)
LOCAL_MODULE := libgrallocclient
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libgrallocclient
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# grallocgmm
include $(CLEAR_VARS)
LOCAL_MODULE := libgrallocgmm
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libgrallocgmm
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# i965_drv_video
include $(CLEAR_VARS)
LOCAL_MODULE := i965_drv_video
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := i965_drv_video
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libivp
include $(CLEAR_VARS)
LOCAL_MODULE := libivp
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libivp
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# lib2d
include $(CLEAR_VARS)
LOCAL_MODULE := lib2d
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := lib2d
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libcoreuclient
include $(CLEAR_VARS)
LOCAL_MODULE := libcoreuclient
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libcoreuclient
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libcoreuinterface
include $(CLEAR_VARS)
LOCAL_MODULE := libcoreuinterface
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libcoreuinterface
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libcoreuservice
include $(CLEAR_VARS)
LOCAL_MODULE := libcoreuservice
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libcoreuservice
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libgsmgr
include $(CLEAR_VARS)
LOCAL_MODULE := libgsmgr
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libgsmgr
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libskuwa
include $(CLEAR_VARS)
LOCAL_MODULE := libskuwa
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libskuwa
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libGLES_ufo_intel7
include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_ufo_intel7
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_RELATIVE_PATH := egl
LOCAL_MODULE_STEM_32 := libGLES_intel7
LOCAL_MODULE_STEM_64 := libGLES_intel7
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/libGLES_intel7$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/libGLES_intel7$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libuevent
include $(CLEAR_VARS)
LOCAL_MODULE := libuevent
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libuevent
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# libmd
include $(CLEAR_VARS)
LOCAL_MODULE := libmd
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libmd
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# igfxcmjit32
include $(CLEAR_VARS)
LOCAL_MODULE := igfxcmjit32
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := igfxcmjit32
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

# igfxcmrt32
include $(CLEAR_VARS)
LOCAL_MODULE := igfxcmrt32
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := igfxcmrt32
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := x86/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
LOCAL_SRC_FILES_64 := x86_64/$(LOCAL_MODULE_STEM)$(TARGET_SHLIB_SUFFIX)
include $(BUILD_PREBUILT)

endif # BOARD_HAVE_GEN_GFX_SRC
